[package]
name = "marlinbox-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rodio = "0.19.0"
rusb = "0.9.4"
serde = { version = "1.0.210", features = ["derive", "rc"] }
serde_json = "1.0.132"
